name = "War"
uuid = "38b49244-42de-43b2-ad8c-ea0a6bf2444f"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.1.0"



[deps]
PlayingCards52 = "c2ceccfa-fa3a-4f0d-8d5f-27465c1854bf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1"
PlayingCards52 = "0.1, 0.2"
DataStructures = "0.18, 0.19"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
